### ISSUE TITLE
readImageSize() must be of the type string or null, array returned

### ISSUE THREAD

**Issue by readtedium** [balazscsaba2006/craft3-amplify#1]
Hi there,

Was futzing around with this plugin today and ran into some problems with how it handled images, throwing this error my way:

` Return value of humandirect\amplify\twig\TwigExtensions::readImageSize() must be of the type string or null, array returned `

The problem line appears to be this portion of TwigExtensions.php:

` private function readImageSize(string $url): ?string `

But changing it to 

` private function readImageSize(string $url): ?array `

makes it work without issues. So it might be worth an update.

If it matters at all, my content editor is Doxter. Thanks!

**Comment by readtedium** [comment]
Added a pull request for this.

**Comment by balazscsaba2006** [comment]
Thanks @readtedium, merged #2

**Comment by readtedium** [comment]
Hi, @balazscsaba2006, this edit regressed out with your last update, mind re-adding?
