### ISSUE TITLE
ParseError with array assignment

### ISSUE THREAD

**Issue by aaronbushnell** [balazscsaba2006/craft3-amplify#3]
Thanks for your work on this plugin!

I'm running a Digital Ocean/ServerPilot server and trying to use Craft CLI to perform some console commands. However, when I run `./craft help` I get:

```
Exception 'ParseError' with message 'syntax error, unexpected '=''

in /vendor/balazscsaba2006/amplify/src/twig/TwigExtensions.php:131
```

And I think it's [referencing this](https://github.com/balazscsaba2006/craft3-amplify/blob/master/src/twig/TwigExtensions.php#L131)
```
[$width, $height] = $size;
```

I'm not sure why this is causing an issue in this environment. I'm running PHP 7.2 and not entirely sure why this is causing problems. Any ideas?

**Comment by balazscsaba2006** [comment]
Hi @aaronbushnell . Just saw the issue. Dod you solve it in the meantime? If yes, please create a pull request so I can merge it. Thanks.
