### ISSUE TITLE
Question:  What is reason for stripping square brackets?

### ISSUE THREAD

**Issue by john-henry** [balazscsaba2006/craft3-amplify#7]
Hi there,

Can I ask about this line in your plugin? https://github.com/balazscsaba2006/craft3-amplify/blob/master/src/twig/TwigExtensions.php#L56

What is the reason for stripping out brackets in general?

Particularly as we use Markdown in our text fields we ran into an issue or two

**Comment by balazscsaba2006** [comment]
Hi @john-henry . My implementation is based on https://github.com/adamsmt/amplify. The exact line where in the original repo strips out the brackets is here: https://github.com/adamsmt/amplify/blob/master/amplify/twigextensions/AmplifyTwigExtension.php#L34

I can't think of a good reason to strip out brackets, so if you'll create a PR I will surely accept it if it works for you.

Best,
Cs.
